"""Operator profile: day-to-day work without company administration."""

OPERATOR_TOOL_NAMES: frozenset[str] = frozenset(
    {
        # Cards (no delete — archive only)
        "kaiten_list_cards",
        "kaiten_get_card",
        "kaiten_create_card",
        "kaiten_update_card",
        "kaiten_archive_card",
        "kaiten_move_card",
        "kaiten_list_all_cards",
        # Spaces (no delete)
        "kaiten_list_spaces",
        "kaiten_get_space",
        "kaiten_create_space",
        "kaiten_update_space",
        # Board navigation (read-only)
        "kaiten_list_boards",
        "kaiten_get_board",
        "kaiten_list_columns",
        "kaiten_list_lanes",
        # Custom properties
        "kaiten_list_custom_properties",
        "kaiten_get_custom_property",
        "kaiten_create_custom_property",
        "kaiten_update_custom_property",
        "kaiten_delete_custom_property",
        "kaiten_list_select_values",
        "kaiten_get_select_value",
        "kaiten_create_select_value",
        "kaiten_update_select_value",
        "kaiten_delete_select_value",
        # Projects & sprints (add cards only; no project delete/update)
        "kaiten_list_projects",
        "kaiten_get_project",
        "kaiten_list_project_cards",
        "kaiten_add_project_card",
        "kaiten_list_sprints",
        "kaiten_create_sprint",
        "kaiten_get_sprint",
        "kaiten_update_sprint",
        # Charts & compute jobs
        "kaiten_get_chart_boards",
        "kaiten_chart_summary",
        "kaiten_chart_block_resolution",
        "kaiten_chart_due_dates",
        "kaiten_chart_cfd",
        "kaiten_chart_control",
        "kaiten_chart_spectral",
        "kaiten_chart_lead_time",
        "kaiten_chart_throughput_capacity",
        "kaiten_chart_throughput_demand",
        "kaiten_chart_task_distribution",
        "kaiten_chart_cycle_time",
        "kaiten_chart_sales_funnel",
        "kaiten_get_compute_job",
        "kaiten_cancel_compute_job",
        # Members & users
        "kaiten_list_card_members",
        "kaiten_add_card_member",
        "kaiten_remove_card_member",
        "kaiten_list_users",
        "kaiten_get_current_user",
        # Comments
        "kaiten_list_comments",
        "kaiten_create_comment",
        "kaiten_update_comment",
        "kaiten_delete_comment",
        # Tags on cards (no company-level tag admin)
        "kaiten_list_tags",
        "kaiten_add_card_tag",
        "kaiten_remove_card_tag",
        # Checklists
        "kaiten_list_checklists",
        "kaiten_create_checklist",
        "kaiten_update_checklist",
        "kaiten_delete_checklist",
        "kaiten_list_checklist_items",
        "kaiten_create_checklist_item",
        "kaiten_update_checklist_item",
        "kaiten_delete_checklist_item",
        # Blockers
        "kaiten_list_card_blockers",
        "kaiten_create_card_blocker",
        "kaiten_get_card_blocker",
        "kaiten_update_card_blocker",
        "kaiten_delete_card_blocker",
        # Time logs
        "kaiten_list_card_time_logs",
        "kaiten_create_time_log",
        "kaiten_update_time_log",
        "kaiten_delete_time_log",
        # Parent/child relations (no planned/Gantt)
        "kaiten_list_card_children",
        "kaiten_add_card_child",
        "kaiten_remove_card_child",
        "kaiten_list_card_parents",
        "kaiten_add_card_parent",
        "kaiten_remove_card_parent",
        # Tree
        "kaiten_list_children",
        "kaiten_get_tree",
        # Documents (no delete)
        "kaiten_list_documents",
        "kaiten_create_document",
        "kaiten_get_document",
        "kaiten_update_document",
        "kaiten_list_document_groups",
        "kaiten_create_document_group",
        "kaiten_get_document_group",
        "kaiten_update_document_group",
        # Activity & saved filters (no audit_logs)
        "kaiten_get_card_activity",
        "kaiten_get_space_activity",
        "kaiten_get_company_activity",
        "kaiten_get_card_location_history",
        "kaiten_get_all_space_activity",
        "kaiten_list_saved_filters",
        "kaiten_create_saved_filter",
        "kaiten_get_saved_filter",
        "kaiten_update_saved_filter",
        "kaiten_delete_saved_filter",
        # Company (read-only)
        "kaiten_get_company",
    }
)
